# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 2-Select_Veg_Points_By_Project_Number_arcmap_export.py
# Created on: 2019-07-15 16:46:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Veg_Points_2_Projects_Join__2_ = "Veg_Points_2_Projects_Join"
Veg_Points_2_Projects_Join__3_ = Veg_Points_2_Projects_Join__2_

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Veg_Points_2_Projects_Join__2_, "NEW_SELECTION", "Proj_Order = 6")

