let
    Source = Json.Document(Web.Contents("https://services9.arcgis.com/xW49QhDgcgjm4BU0/arcgis/rest/services/BANGOR_1101_V7_EVM_Veg_092019/FeatureServer/0/query?where=%28%22Division%22+%3D+%27SI_Sierra%27%29+AND+%28%22INS_DATE%22+%3C+%28CURRENT_DATE+-1%29%29+AND+%28%22INS_DATE%22+%3E+%28CURRENT_DATE+-2%29%29&objectIds=&time=&geometry=&geometryType=esriGeometryPoint&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=INS_DATE+ASC&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token=73tfO9dshNAWBYF230dbnrIp7tS7pEbQkB-e8ifNxotunrLACwgF6EYQo_gu2bnWFT4N9ubpboyryeg5qLe241pmsK2x00nmd_fE6eT8LENskX4JizKAe5prcmUmYbGPAyFMCx0LsHpfezun7zXdE6QUlk7cAd550uSh0jju7q8ChhQIPWUvBI1W9hGwEtSEXPZo0-YvSQNanRXWp_kh00kynvXyX1183IH1PdePUjw."), 65001),
    features = Source[features],
    #"Converted to Table" = if List.IsEmpty(features)=true then Table.FromList({}, null, {"Column1"}) else Table.FromList(features, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"attributes", "geometry"}, {"attributes", "geometry"}),
    #"Expanded attributes" = Table.ExpandRecordColumn(#"Expanded Column1", "attributes", {"OBJECTID", "Change_From_AWRR_To_EVM", "STATUS", "Collector_Username", "INS_DATE", "PI_COMPANY", "PI_COMMENTS", "VEG_TYPE", "SPECIES", "DIAMETER", "HEIGHT", "PRESCRIP", "Tree_Matrix_Score", "Impact_Matrix_Score", "Additional_Work", "UNDERBUILD", "RWD_EXC", "WOOD_MAN", "WM_Work_Type", "WM_COMMENTS", "WM_Company", "WM_Date", "CRANE", "TRAFFIC", "LINE_KILL", "RIPARIAN", "CALTRANS", "ENC_PERMIT", "PERMIT", "AMMS", "BMPS", "CREW_LANID", "TW_COMPANY", "TW_SUB", "WORK_DATE", "ACT_WORK", "TW_COMMENTS", "Billing_Type", "POINT_ID", "PARCEL_ID", "CIRCUITNAME", "UNIQUE_SEGMENT_ID", "AUTO_ID", "REGION", "Division", "PARCEL_NAME", "SITE_ADDRESS", "PROPERTY_CITY", "Created", "Editor", "Edited", "PROJECT_ID", "Creator", "GlobalID", "EVM_LAST_EDITOR", "EVM_LAST_EDITED", "EVM_SYNC_ID"}, {"OBJECTID", "Change_From_AWRR_To_EVM", "STATUS", "Collector_Username", "INS_DATE", "PI_COMPANY", "PI_COMMENTS", "VEG_TYPE", "SPECIES", "DIAMETER", "HEIGHT", "PRESCRIP", "Tree_Matrix_Score", "Impact_Matrix_Score", "Additional_Work", "UNDERBUILD", "RWD_EXC", "WOOD_MAN", "WM_Work_Type", "WM_COMMENTS", "WM_Company", "WM_Date", "CRANE", "TRAFFIC", "LINE_KILL", "RIPARIAN", "CALTRANS", "ENC_PERMIT", "PERMIT", "AMMS", "BMPS", "CREW_LANID", "TW_COMPANY", "TW_SUB", "WORK_DATE", "ACT_WORK", "TW_COMMENTS", "Billing_Type", "POINT_ID", "PARCEL_ID", "CIRCUITNAME", "UNIQUE_SEGMENT_ID", "AUTO_ID", "REGION", "Division", "PARCEL_NAME", "SITE_ADDRESS", "PROPERTY_CITY", "Created", "Editor", "Edited", "PROJECT_ID", "Creator", "GlobalID", "EVM_LAST_EDITOR", "EVM_LAST_EDITED", "EVM_SYNC_ID"})
in
    #"Expanded attributes"