# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# HTRS_Errors_Narrows.exp.py
# Created on: 2019-11-07 15:33:07.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Vegetation_Point = "NARROWS_2102_V7_EVM_Veg_092019\\Vegetation Point"
Vegetation_Point__2_ = Vegetation_Point
Expression = "(((\"STATUS\" = 'Work Identified' ) OR ( \"STATUS\" = 'In-Progress' )) AND ((\"Tree_Matrix_Score\" = NULL) OR (\"Tree_Matrix_Score\" = '') OR ( \"Impact_Matrix_Score\" = NULL ) OR ( \"Impact_Matrix_Score\" = '' )))"
Vegetation_Point__3_ = Vegetation_Point__2_
Expression__2_ = "\"INS_DATE\" > date '2019-09-30 23:52:29'"

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(Vegetation_Point, "NEW_SELECTION", Expression)

# Process: Select Layer By Attribute (2)
arcpy.SelectLayerByAttribute_management(Vegetation_Point__2_, "SUBSET_SELECTION", Expression__2_)

